print("hello world i am learning python")
print("sixty billion dollars")
print("An escalade")
print(23)
print("23")
name= "Olamide"
print(name)
print("my name is"+ name)
print("my name is" + name)
print("my name is "+name)
print("my name is " +" "+ name)
print("f""hello{name}")
print("f""hello{Olamide}")
print(f"{name}")
